services:
      nginx:
        image: nginx:latest
        container_name: my_first_nginx
        ports:
             - 5000-80

      mynewapache:
        image: ubuntu/apache2:latest
        container_name: my_first_apache
        ports:
              - 5001-80


